### ISSUE TITLE
Add traceable actions in Notifications module.

### ISSUE THREAD

**Issue by AntonLV** [boonex/trident#165]
1. Comment posted.
2.

**Comment by LiNetKurando** [comment]
- someone subscribed your profile
- got a 'thumbs up' on a (timeline)post

**Comment by LiNetKurando** [comment]
- someone subscribed your profile
- got a 'thumbs up' on a (timeline)post

**Comment by LiNetKurando** [comment]
- someone posted on your timeline

**Comment by AntonLV** [comment]
Added actions are:
1. New comment
2. New vote
Note. Currently the module is used to get Notifications about events which are comming from members you are subscribed to. So, it cannot be used to get notifications related to your own profile.

**Comment by AntonLV** [comment]
Related: Ticket #241
