### ISSUE TITLE
Timeline: share a link issue 

### ISSUE THREAD

**Issue by AlexTr** [boonex/trident#168]
when you share a link to timeline, you have to enter the whole link ie "http://www.online.me" ... if you post it as "www.online.me" , or "online.me" it will lead to 404 not found page.

http://www.boonex.com/forums/topic/Share-a-link-issue.htm

**Comment by AntonLV** [comment]
Cannot reproduce the issue. Tested on Demozzz Trident.
1. Share: http://www.online.me - OK
2. Share: www.online.me - OK
3. Share: online.me - Share form gives an error "Correct Link is essential. Please, fill in this field."

**Comment by AlexTr** [comment]
Please check latest Timeline posts here - http://www.online.me/page/view-persons-profile&id=58
"Share: www.online.me - OK" - yes, it is shared, but when you click on the link it doesn't work.
Also for some reason it can't get title from boonex.com, maybe because of the icon in the title. Also when site has no title, it should still display the link as domain name.
