### ISSUE TITLE
Language keys in share buttons don't get parsed (title-attribute)

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#201]

**Comment by AlexTr** [comment]
@LiNetKurando  Please could you clarify what you mean ?

**Comment by LiNetKurando** [comment]
If you hover one of the share-buttons, the language-key in the title-attribute of the button is not getting parsed. 
This one (taken from online.me):
![unbenannt20151016000213](https://cloud.githubusercontent.com/assets/13453103/10528855/2fc45bb2-7399-11e5-812f-8015583dc5f3.png)

**Comment by AlexTr** [comment]
thank you @LiNetKurando for clarification
