### ISSUE TITLE
Post to Timeline in + Menu

### ISSUE THREAD

**Issue by Zarconia** [boonex/trident#226]
I would like to suggest adding a Post To Timeline in the + menu option in the top right corner. This way, users can go directly to the timeline to make posts. 

Also, I would like to see Timeline posts be displayed in the Outline. Example, my Trident site ONLY has the Outline on the homepage. Being able to see ALL posts (Albums, Posts, Timeline, etc) on the homepage gives the members immediate access to new content that has been posted in all features.

**Comment by AlexTr** [comment]
It's privacy issue to display Timeline posts in Outline. We already have such concern in Dolphin.Pro and we'll remove this feature there.

**Comment by Zarconia** [comment]
I can see where that may be an issue. Maybe incorporate a way to set the privacy level to each post (Public, members, friends/subscribers)? So the user has the option to choose which level of privacy per post. So if someone chooses 'Public' it would get displayed in the Outline visible to all. Members would be visible only of logged in, etc.. Just suggestions

**Comment by andrewboon** [comment]
So, each timeline post should have a "Privacy" setting dropdown with options "Public/Friends/Only Me". 

A little later Timeline Posts should be turned off by default, and "Post to Timeline" form should be a quick-post form for module-posts, such as Notes and Albums, etc. Privacy selection should still remain though.

**Comment by AlexTr** [comment]
We can't add privacy to each post, because of the following:
1) It will be a situation when owner couldn't see timeline posts on own timeline
2) It's very problematic to check each post privacy especially on public timeline
3) Public timeline will not be public anymore
