### ISSUE TITLE
Remove "Not a member yet? Join now!" from login block by default.

### ISSUE THREAD

**Issue by andrewboon** [boonex/trident#238]
The sign-up line should also be optional, or users can add it using additional block. This is required, because often sign-up option has to be added as a more prominent block, or a full sign up form and it doesn't look right, when there is a link to sign up duplicated in login form.

**Comment by AntonLV** [comment]
Related Ticket #239. We decided to create additional Login block without this link. However by default the block with the text is used and newly created one is hidden.
