### ISSUE TITLE
Streamline login form.

### ISSUE THREAD

**Issue by andrewboon** [boonex/trident#239]
Remove HR and sign up text, center "forgot" password under the sign in button. Use all-caps for button text, and use extra-wide button style.

![image](https://cloud.githubusercontent.com/assets/3324885/10534961/09a41b84-742a-11e5-85ac-04d00b8a3564.png)

![image](https://cloud.githubusercontent.com/assets/3324885/10534987/3c3245da-742a-11e5-8df3-5f2dfff99699.png)

**Comment by AntonLV** [comment]
If I remove "Not a member yet? Join now!" from join form we should display it some other place which is available on ALL pages. Beacuse we would have only one JOIN link which is available on a splash screen.
P.S. Sometimes ago we had a problem that it was too hard to find a JOIN link. We added this one in login form.

**Comment by AlexTr** [comment]
Ok, leave this text for now, but make other changes

**Comment by andrewboon** [comment]
The reason why I think "JOIN" text shoudl be removed is that webmaster can always add a short join block where needed, if needed. But in many situation the JOIN link may not be needed and it's hard to remove it from the login box for webmaster. For example, situaiton when I build a "join/login' page, where both forms are present. Or, when I want a more prominent "JOIN" block on the side, with a banner and some text. 

When building trident.social I found that I would have more/better flexibility if JOIN form or link or text would be a property of separate block that I can add/edit when needed.
