### ISSUE TITLE
mistake on pre release to download

### ISSUE THREAD

**Issue by camperjz** [boonex/trident#240]
8.0.0-B2
@AlexTr AlexTr released this on 7 May

Trident v.8.0.0-B2 (beta 2)
Almost production ready, upgradable
Downloads

(30.4 MBDolphin-v.7.2.0.B2.zip)
-v.7.2.0.B2.zip must be  Trident-v.8.0.0-B2.zip

**Comment by AlexTr** [comment]
Fixed.
Thank you for pointing this out.
