### ISSUE TITLE
Apply visibility-settings to form-validation

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#242]
Short: The visibility-settings of fields don't apply to the validation- and saving-part of forms - just the display. (visibility = membership-level)

[applies to non-admins]
If I set the visibility of an form input to admin- and mod-only, the form itself is *displayed* correctly.
Means: A normal user can't see the input field.
But when the user saves/submits the form, the system validates even the "hidden" fields.

If I set the visibility of the username-field to admins-only, a normal user can't see it, but if he saves he gets an error (please check the form for correct input etc.).

If an admin-only field doesn't contain a validation-rule (example: not required), the data of this field will be empty, after the user saved.

**Comment by AlexTr** [comment]
Great finding!
