### ISSUE TITLE
Installation from online.me continuous integration link broken

### ISSUE THREAD

**Issue by Adam24** [boonex/trident#246]
The version of trident downloaded direct from the servers at online.me seem to be broken in a lot of areas such as the create-persons-profile page and a lot of others. Might want to fix that or repair it.

**Comment by AlexTr** [comment]
Thank you for the report. Please could you describe the problem in more details ?

**Comment by Adam24** [comment]
the build on the main site lacks the .htaccess file for URL paths to work
causing most functions to return 404s.

On Mon, Nov 9, 2015 at 5:24 PM, Alex Trofimov <notifications@github.com>
wrote:

> Thank you for the report. Please could you describe the problem in more
> details ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonex/trident/issues/246#issuecomment-155231307>.
>



-- 
--Adam Robertson-- (write back)

**Comment by AlexTr** [comment]
I've just checked latest beta2 package and latest automated build - .htaccess presents in both packages. Please note that .htaccess file is hidden file and some ftp managers can't see it.

**Comment by AmineBAIK1** [comment]
Same issue here, How to fix it ?
