### ISSUE TITLE
Include TinyMCE library for forms

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#297]
I noticed some time ago, that if I have a HTML editor enabled in a form field and use this form in a popup (example: I have a grid with an add-button. When I click on the button, a popup with the form opens), the editor is missing / not working right.

The library for the editor should be included automatically - even if the form is opend in a popup.

**Comment by AntonLV** [comment]
Not reproducible.
TinyMCE editor appears in popup without any problems in Studio -> Pages -> Html block.
Also I tried to use TinyMCE in Studio -> Polyglot -> Keys (Grid based) -> Add/Edit Key. By default there is no TinyMCE there but I manually enabled it and editor loaded in the popup without any problems too.
