### ISSUE TITLE
Market: File uploader is not opening + not required

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#310]
File uploader is not opening (error in console): glUploader_BhPeXE59_bx_market_html5 is not defined

Product can be add even without files. But then the download-button is displayed and when clicking on it the following message appears (since I uploaded no files):

Warning: Invalid argument supplied for foreach() in /home/ciboonex/public_html/trident/modules/boonex/market/classes/BxMarketTemplate.php on line 210

**Comment by AntonLV** [comment]
RE: _File uploader is not opening (error in console): glUploader_BhPeXE59_bx_market_html5 is not defined._
Cannot reproduce the issue. 
The rest were fixed.
