### ISSUE TITLE
I have no clue what to do with these errors

### ISSUE THREAD

**Issue by newton27** [boonex/trident#319]
Open RCT2 Community Man of Teal | Open RCT2 Multiplayer Verification
The following errors appeared during modules upgrade:

English module: Check the script version for compatibility: The new version of English module isn't compatible with your version of Trident. Please upgrade Trident first (Studio > Dashboard > Version) and then try to upgrade the module.
Persons module: Check the script version for compatibility: The new version of Persons module isn't compatible with your version of Trident. Please upgrade Trident first (Studio > Dashboard > Version) and then try to upgrade the module.

After trying this procedure above, the site reports the same.

**Comment by newton27** [comment]
In the inc version.inc.php is see version
BX_DOL_VERSION', '8.0.1'

in the English module folder the update is 
update_8.0.12_9.0.0

shouldn't this be  update_8.0.1_9.0.0

**Comment by AlexTr** [comment]
We've published new versions of modules which are compatible with new version of Trident.
These module updates can be applied after core is updated to v.9.0.0. 
9.0.0.B1 is coming is a few days.

**Comment by newton27** [comment]
OK, thanks Alex on this question.
