### ISSUE TITLE
Upgraded test site to 9.0 getting Fatal error 

### ISSUE THREAD

**Issue by Itsawhiz** [boonex/trident#324]
Confirmed also happening on Online.me Seems to be with Lagoon template only
Fatal error: bx_import fatal error: class (BxTemplCover) wasn't found in /home/onlineme/public_html/inc/utils.inc.php on line 630

**Comment by AlexTr** [comment]
This problem occurs because Lagoon template in Trident 8.0 was replaced with Protean template in Trident 9.0. Upgrade script adds Protean template by default. So make sure that you've installed Protean template after upgrade is completed.
