### ISSUE TITLE
Resize popup box after html-editor loaded

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#337]
If a popup box opens and contains an editor (example: edit html block in studio), the popup box just resizes BEFORE the editor (toolbar etc.) is loaded.
This results into the problem, that the content is getting higher, but the popup stays at the same (lower) position. The box is not scrollable - you can't the the lower content in the popup.

So the popup should be resized (again) AFTER the editor is initialized.

**Comment by AntonLV** [comment]
not reproducible
