### ISSUE TITLE
No editor content after canceling in block

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#341]
Want to edit an language-key block. Popup opens, editor loaded, editor prefilled with the current content.
When I click on CANCEL and then reopen that open (just edit that item again) the editor is empty (not prefill with current data) and I'm not able to edit the content in the editor.

**Comment by LiNetKurando** [comment]
HTML blocks have a strange behaviour, too. But there the whole editor disappears.

**Comment by AlexTr** [comment]
https://github.com/boonex/trident/issues/386
