### ISSUE TITLE
Replace button on downloaded store items

### ISSUE THREAD

**Issue by LiNetKurando** [boonex/trident#358]
Downloaded - but not installed modules - display a grayed-out download-button in the popup.
The button should change according to its state.

Not downloaded: Download
Not installed: Install, Delete
Installed: Deinstall

![screen](https://cloud.githubusercontent.com/assets/13453103/17052793/41a56568-4fff-11e6-8963-6c0021460d05.png)

**Comment by AlexTr** [comment]
There are two different sections:
- Storefront: modules can be purchased and downloaded
- Downloaded: modules can be installed and deleted

There is no section to download and install at the same place.
