### ISSUE TITLE
there is a problem with the groups and the admin

### ISSUE THREAD

**Issue by newton27** [boonex/trident#364]
when trying to view notifications about the groups module I'm getting a 500 error

> I will add the error shortly but need to get this up..
> I went to this screen.
> ![group button meanings](https://cloud.githubusercontent.com/assets/4349640/17312121/8ad9e782-581e-11e6-9fd4-fb5f28812194.JPG)

then notices seven notifications bubble, and when viewing that page the 500 error.
If I remove myself from the group as the admin name and view the notifications, I see them as long as I don't join the group. 
sorry for the vague post. I can duplicate on my site if needed again.

**Comment by newton27** [comment]
The main reason I found the problem because I want to know what the buttons mean/do?
From Admins, To Admins

**Comment by newton27** [comment]
all to a member function isAdmin() on a non-object in /home/site/public_html/modules/base/groups/classes/BxBaseModGroupsPrivacyNotifications.php on line 27, referer: https://site.com/page/group-fans&profile_id=516

**Comment by AlexTr** [comment]
The issue should be fixed in #308
