### ISSUE TITLE
Page Builder: cover options

### ISSUE THREAD

**Issue by AlexTr** [boonex/trident#380]
Add new tab for the page in page builder with 2 fields:
1) enable/disable cover
2) upload custom cover

**Comment by AlexTr** [comment]
@AntonLV I think we can remove "Home page cover" from Studio > Designer since it can be changed from Page Builder.

**Comment by camperjz** [comment]
![tridentdev index php](https://cloud.githubusercontent.com/assets/8642312/17727077/22e842a0-6457-11e6-86dd-cb02c4cce7e2.png)
 i have install this repo today to test and get cover Studio Dashboard on the splash page olso when you logout

**Comment by AlexTr** [comment]
@AntonLV Cover should be disable for Splash by default.
