### ISSUE TITLE
Protean styles: can't override styles of sliding menu and submenu and other issues

### ISSUE THREAD

**Issue by AlexTr** [boonex/trident#405]
1. can't override styles of sliding menu
2. can't override styles of submenu menu
3. block headers can’t support a border radius 
4. need to be able to override the non-link text in the slide menu also. Right now it’s fixed to whatever color the h1 font is set to.

1-2. will probably better overrode using custom css, but 3-4 should be addressed.

**Comment by andrewboon** [comment]
@AlexTr  test
